// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjiF8usAP4vpgfEjbBh0Je6JRKihsc-BY',
    appId: '1:11038204174:web:8d681109fb19e40c4b775f',
    messagingSenderId: '11038204174',
    projectId: 'flutter-firebase-568e9',
    authDomain: 'flutter-firebase-568e9.firebaseapp.com',
    storageBucket: 'flutter-firebase-568e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60RURllw2nTgR_Gf0qe-_fdqaFPDsB60',
    appId: '1:11038204174:android:b78dea54aba5403b4b775f',
    messagingSenderId: '11038204174',
    projectId: 'flutter-firebase-568e9',
    storageBucket: 'flutter-firebase-568e9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjiF8usAP4vpgfEjbBh0Je6JRKihsc-BY',
    appId: '1:11038204174:web:40bd99471dcc9d3a4b775f',
    messagingSenderId: '11038204174',
    projectId: 'flutter-firebase-568e9',
    authDomain: 'flutter-firebase-568e9.firebaseapp.com',
    storageBucket: 'flutter-firebase-568e9.firebasestorage.app',
  );
}
